{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "telco-deps.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.namespace }}
  {{- if .Values.linkerdInject }}
  annotations:
    linkerd.io/inject: enabled
  {{- end }}
{{- end }}
